### PR TITLE
[fix][compat] iris shaders

### LINKED ISSUE #172: In-game Iris menu loads with dirt background.
When using Bedrockify with Iris on 1.19.2, the in-game iris shaders menu renders with the dirt background instead of showing the game in the background.

### PR DESCRIPTION
**Pull request by lonefelidae16**
fixes #172 

Use the constructor to set fields `renderBackground` and `renderHorizontalShadows` that they can be changed by other MOD. Please check the changes below:

* `EntryListWidgetMixin.java`
  - methods `doNotDrawBackground(EntryListWidget)` and `doNotDrawBars(EntryListWidget)` were removed
  - new method `bedrockify$ctor` was added which targeted to constructor of `EntryListWidget`

### CODE REVIEW

File: src/main/java/me/juancarloscp52/bedrockify/mixin/client/features/panoramaBackground/EntryListWidgetMixin.java [hunk 1]
```diff
@@ -34,21 +36,19 @@ private void renderPanorama(EntryListWidget entryListWidget, MatrixStack matrice
         }
     }
 
-    // Prevent the screen background from drawing
-    @Redirect(method = "render", at=@At(value = "FIELD",target = "Lnet/minecraft/client/gui/widget/EntryListWidget;renderBackground:Z", opcode = Opcodes.GETFIELD))
-    private boolean doNotDrawBackground(EntryListWidget entryListWidget){
-        return !Bedrockify.getInstance().settings.isCubemapBackgroundEnabled() || shouldIgnoreScreen();
+    @Inject(method = "<init>(Lnet/minecraft/client/MinecraftClient;IIIII)V", at=@At("TAIL"))
```
Comment (lonefelidae16) [inline src/main/java/me/juancarloscp52/bedrockify/mixin/client/features/panoramaBackground/EntryListWidgetMixin.java]:
```suggestion
    @Inject(method = "<init>(Lnet/minecraft/client/MinecraftClient;IIIII)V", at=@At("RETURN"))
```

Should we use `RETURN` in At annotation?

https://fabricmc.net/wiki/tutorial:mixin_injects says

> **RETURN** Before *every* return statement
> **TAIL** Before *the final* return statement

It might be more compatible with other MOD that use `cancelable=true` and `CallbackInfo#cancel`.

**Review by lonefelidae16 — COMMENTED** [review]
I read over my code and had a thought, so I’ll review it myself.

**Comment by lonefelidae16** [comment]
update: for `EntryListWidgetMixin.java`
- use Shadow annotation to get the original methods instead of casting `this`
- use `RETURN` in At annotation of constructor
- deleted unnecessary import statement

**Comment by juancarloscp52** [comment]
Looks good! Thanks!
